services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyStrong!Password"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P MyStrong!Password -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
  bobit-api:
    image: ${DOCKER_REGISTRY-}bobitapi
    container_name: bobit-api
    build:
      context: .
      dockerfile: Bobit.Api/Dockerfile
    depends_on:
      - mssql-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=mssql-db;Database=BitcoinDB;TrustServerCertificate=True;User Id=sa;Password=MyStrong!Password
      - ConnectionStrings__MasterConnection=Server=mssql-db;Database=master;TrustServerCertificate=True;User Id=sa;Password=MyStrong!Password
    ports:
      - "5210:8080"
      - "7214:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  bobit-fetcher:
    image: ${DOCKER_REGISTRY-}bobitfetcher
    container_name: bobit-fetcher
    build:
      context: .
      dockerfile: BoBit.Fetcher/Dockerfile
    depends_on:
      - mssql-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=mssql-db;Database=BitcoinDB;TrustServerCertificate=True;User Id=sa;Password=MyStrong!Password
      - ConnectionStrings__MasterConnection=Server=mssql-db;Database=master;TrustServerCertificate=True;User Id=sa;Password=MyStrong!Password
    ports:
      - "5117:8080"
      - "7189:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  bo-bit-site:
    image: ${DOCKER_REGISTRY-}bobitsite
    container_name: bo-bit-site
    build:
      context: ./bo-bit-site
      dockerfile: Dockerfile
    environment:
      - API_URL=https://bobit-api
    ports:
      - "4200:80"
  
