services:
  mssql-db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyStrong!Password"
    ports:
      - "1433:1433"
    #volumes:
    #  - mssql-data:/var/opt/mssql
  bobit-fetcher:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=mssql-db;Database=BitcoinDB;TrustServerCertificate=True;User Id=sa;Password=MyStrong!Password
      - ConnectionStrings__MasterConnection=Server=mssql-db;Database=master;TrustServerCertificate=True;User Id=sa;Password=MyStrong!Password
    ports:
      - "5117:8080"
      - "7189:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro